name: remanga_secret_tools
description: "A collection of unofficial tools and utilities that unlock hidden features and enhance the Remanga experience."
publish_to: "none"

version: 0.1.5

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^11.1.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flex_color_scheme: ^8.4.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.3
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  hydrated_bloc: ^10.1.1
  json_annotation: ^4.9.0
  retrofit: ^4.9.1
  sentry_flutter: ^9.9.1
  shimmer: ^3.0.0
  talker: ^5.1.9
  talker_flutter: ^5.1.9
  talker_bloc_logger: ^5.1.9
  talker_dio_logger: ^5.1.9
  url_launcher: ^6.3.2
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  retrofit_generator: 10.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Exo 2
      fonts:
        # - asset: assets/fonts/Exo2-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Exo2-Regular.ttf
          weight: 400
        # - asset: assets/fonts/Exo2-Medium.ttf
        #   weight: 500
        - asset: assets/fonts/Exo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
        # - asset: assets/fonts/Exo2-ExtraBold.ttf
        #   weight: 800
