name: backend
description: Backend service for Remanga Secret Tools, aggregating data and powering unofficial features for the Remanga ecosystem.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  crypto: ^3.0.7
  dart_frog: ^1.1.0
  dio: ^5.9.0
  dotenv: ^4.2.0
  drift: ^2.29.0
  drift_postgres: ^1.3.1
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  json_annotation: ^4.9.0
  meta: ^1.17.0
  postgres: ^3.5.9
  redis: ^4.0.0
  retrofit: ^4.9.1
  shelf_cors_headers: ^0.1.5
  shelf_limiter: ^2.0.1
  talker: ^5.1.3
  talker_dio_logger: ^5.1.3

dev_dependencies:
  build_runner: ^2.10.4
  dart_frog_lint: ^0.1.0
  drift_dev: ^2.29.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mocktail: ^1.0.3
  retrofit_generator: ^10.0.1
  test: ^1.25.5
